import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function Topnav(){
  return(
    <nav className="flex w-full items-center justify-between p-4 text-xl font-semibold border-b">
      <div>Client Manager</div>
    </nav>
  )
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>

      <body>
        <Topnav/>
        {children}
      </body>
    </html>
  );
}
